- name: minersapp
  synchronize:
    src: /home/eth/ansible/miners/{{ miner_name }}/{{ miner_name }}/
    dest: /home/eth/{{ miner_name }}/
    delete: true
    recursive: yes

- name: minersapp
  synchronize:
    src: /home/eth/ansible/miners/{{ miner_name }}/miner_config
    dest: /home/eth/miner_config/
    delete: true
    recursive: yes

- name: update address.txt under miner apps folder
  template:
    src: address.j2
    dest: /home/eth/{{ miner_name }}/address.txt
    mode: 0644
    owner: eth
    group: eth

- name: start miner app
  command: chdir=/home/eth/{{ miner_name }} ./run.sh
  become: True
  become_user: eth
  become_method: su
