- name: minersapp
  synchronize:
    src: /home/eth/ansible/miners/{{ miner_name }}/
    dest: /home/eth/
    delete: false
    recursive: yes

- name: update address.txt under miner apps folder
  template:
    src: address.j2
    dest: /home/eth/{{ miner_name }}/address.txt
    mode: 0644
    owner: eth
    group: eth

- name: start miner app
  shell: "cd /home/eth/{{ miner_name }} && ./run.sh"
  become: True
  become_user: eth
  become_method: su
