- name: Kill running processes
  shell: "pkill -9 -f {{ item }}"
  ignore_errors: yes
  become: True
  become_user: root
  become_method: sudo
  with_items: 
    - miner
    - Miner
    - t-rex
    - pool
