- name: Update local apt cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
      - libmicrohttpd10
      - screen
      - ntp
      - monit
      - htop
      - iftop