- name: copy resolv.conf.d/head
  template:
    src: dns/resolv.conf.d_head
    dest: /etc/resolvconf/resolv.conf.d/head
    mode: 0644
    owner: root
    group: root

- name: update /etc/resolv.conf
  blockinfile: |
        dest=/etc/resolv.conf
        content="nameserver 223.5.5.5
              nameserver 223.6.6.6"