- name: copy resolv.conf.d/head
  template:
    src: dns/resolv.conf.d_head
    dest: /etc/resolvconf/resolv.conf.d/head
    mode: 0644
    owner: root
    group: root

- name: update /etc/resolv.conf
  lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver 223.5.5.5"

- name: update /etc/resolv.conf
  lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver 223.6.6.6"
