- name: create dir miner_config
  file:
    path: /home/eth/miner_config
    state: directory
    mode: 0755
    owner: root
    group: root
- name: copy startup.sh
  template:
    src: miner/startup.sh
    dest: /home/eth/miner_config/startup.sh
    mode: 0755
    owner: root
    group: root
