- name: Update local ntp cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day
- name: install ntp
  apt:
    name: ntp
    state: present
- service:
    name: ntp
    state: started
    enabled: yes
