- name: check if cudaX exists
  stat:
    path: /usr/local/cuda-10.0
  register: cuda10

- name: extract cuda10.tgz to remote server
  unarchive:
    src: /home/eth/ansible/cuda/cuda10.tgz
    dest: /usr/local
  when: cuda10.stat.exists == False

- name: /usr/local/cuda symlink
  file:
    src: /usr/local/cuda-10.0
    dest: /usr/local/cuda
    state: link
    force: yes

- name: remove /usr/local/cuda-8.0
  file:
    path: /usr/local/cuda-8.0
    state: absent

- name: check if nvidia-uninstall exists
  shell: command -v nvidia-uninstall >/dev/null 2>&1
  register: nvidia_uninstall
  ignore_errors: yes

- name : check nvidia version match
  shell: nvidia-smi --query-gpu=driver_version --format=csv,noheader | sort -u
  register: nvidia_driver_version
  when: nvidia_uninstall.rc == 0

- name: copy NVIDIA-Linux-Latest.run to remote
  copy:
    src:  /home/eth/ansible/cuda/NVIDIA-Linux-Latest.run
    dest: /tmp/NVIDIA-Linux-Latest.run
    mode: 0755
    owner: root
    group: root
  when: nvidia_uninstall.rc == 0 and nvidia_driver_version.stdout != "430.14"

- name: rmmod nvidia modules
  command: rmmod "{{ item }}"
  with_items:
    - nvidia_drm
    - nvidia_modeset
    - nvidia_uvm
    - nvidia
  when: nvidia_uninstall.rc == 0 and nvidia_driver_version.stdout != "430.14"

- name: uninstall nvidia driver
  command: nvidia-uninstall -s
  when: nvidia_uninstall.rc == 0 and nvidia_driver_version.stdout != "430.14"

- name: install latest nvidia driver
  command: /tmp/NVIDIA-Linux-Latest.run --no-x-check --no-nouveau-check -sX
  when: nvidia_uninstall.rc != 0 or nvidia_driver_version.stdout != "418.43"
  
