- name: copy NVIDIA-Linux-Latest.run to remote
  copy:
    src:  /home/eth/ansible/cuda/NVIDIA-Linux-Latest.run
    dest: /tmp/NVIDIA-Linux-Latest.run
    mode: 0755
    owner: root
    group: root

- name: check if nvidia-uninstall exists
  shell: command -v nvidia-uninstall >/dev/null 2>&1
  register: nvidia_uninstall
  ignore_errors: yes

- name : check nvidia version match
  shell: nvidia-smi --query-gpu=driver_version --format=csv,noheader | sort -u
  register: nvidia_driver_version
  when: nvidia_uninstall.rc == 0

- name: uninstall nvidia driver
  command: nvidia-uninstall -s
  when: nvidia_uninstall.rc == 0 and nvidia_driver_version.stdout != "396.18"

- name: install latest nvidia driver
  command: /tmp/NVIDIA-Linux-Latest.run --no-x-check --no-nouveau-check -sX
  when: nvidia_uninstall.rc != 0 or nvidia_driver_version.stdout != "396.18"
  
