- name: enable service
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
      - ntp
      - monit

- name: disable service
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
      - lightdm
