- name: sshd_config file update
  template: src=ssh/sshd_config dest=/etc/ssh/sshd_config
  notify:
      - restart sshd

- name: ssh_config file update
  template: src=ssh/ssh_config dest=/etc/ssh/ssh_config
