- name: install custom vimrc file
  template:
    src: vim/vimrc
    dest: /etc/vim/vimrc
    mode: 0644
    owner: root
    group: root

- name: ensure ~/.viminfo exists
  file:
    dest: /home/eth/.viminfo
    mode: 0600
    owner: eth
    group: eth
